display_order INT NOT NULL DEFAULT 0,
            display_status VARCHAR(1) NOT NULL DEFAULT 'Y',
            created_by INT NOT NULL DEFAULT 0,
            created_by_name VARCHAR(255) DEFAULT NULL,
            created_by_role INT NOT NULL DEFAULT 0,
            deleted_status VARCHAR(1) NOT NULL DEFAULT 'N',
            deleted_by INT NOT NULL DEFAULT 0,
            deleted_by_name VARCHAR(255) DEFAULT NULL,
            deleted_time DATETIME DEFAULT NULL,
            deleted_time TIMESTAMP DEFAULT NULL,
            created_at TIMESTAMP DEFAULT NULL,
            created_at DATETIME DEFAULT NULL,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP