exports.CONSTANTS = {
    SUCCESS_FLAG: 1,
    FAIL_FLAG : 0,
    TOP_BG_COLOR: "#273F8B",
    LOGO_URL_EMAIL: "https://www.cloudswiftsolutions.com/theme/default/images/logo.png",
    FOOTER_TEXT_COLOR: "#FFF",
    
    COMPANY_NAME: "Demonstration Company",
    COMPANY_ADDRESS : "123 main street,",
    COMPANY_ADDRESS2 : " second addrss",
    COMPANY_CITY : "vadodara",
    COMPANY_STATE: "GJ",
    COMPANY_COUNTRY : "IN",
    COMPANY_ZIPCODE: "390019",
    COMPANY_EMAIL : "mayank.patel104@gmail.com",
    COMPANY_WEBSITE : "www.cloudswiftsolutions.com",
    COMPANY_CONTACT : "+91 9191919191",
    
    DEFAULT_TITLE : "Demonstration Company",
    DEFAULT_META_TITLE : "Demonstration Company",
    DEFAULT_META_DESCRIPTION : "Demonstration Company Description",
    USER_EMAIL_UNIQUE : "N",
    ACCOUNT_SUCCESSFULLY_CREATED: "Account Successfully Created",
    WELCOME_SUBJECT_PREFIX: "Welcome to",
    WELCOME_TO_API : "Welcome to the API. Router is working.",
    PASSWORD_CHANGED_SUCCESSFULLY: "Password Changed Successfully",
    ALLOW_AUTOLOGIN: "N",
    DEFAULT_MESSAGE : "API Is Working",
    DATABASE_CONNECTED : "Database Connected Successfully. Below is testing Data",
    INVALID_CREDENTIALS: "Invalid Login Credentials",
    INVALID_ACCOUNT: "Invalid Account",
    INVALID_TOKEN : "Invalid Token",
    INACTIVE_ACCOUNT : "Your Account Is Inactive",
    DELETED_ACCOUNT: "Your Account Is Deleted",
    FILE_DELETED: "File Is Successfully Deleted",
    REQUEST_SUCCESS: "Your Request Successfully Executed",
    DATA_NOT_FOUND: "Data Not Found",
    REQUEST_FAIL: "Error In Executing Request",
    INVALID_TOKEN_OR_EMAIL: "Invalid Token Or Email",
    EMAIL_SUCCESS_SENT: "Email Successfully Sent",
    EMAIL_FAIL_SENT : "Email Sending Failed",
    PASSWORD_CHANGED : "Your Password Successfully Changed",
    EMAIL_EXISTS: "Email address Already Exists",
    FORGOTPASSWORD_SUBJECT : "Forgot Password ",
    CHANGEPASSWORD_SUBJECT : "Change Password ",
    PASSWORDUPDATED_SUBJECT : "Password Updated",
    
    MYSQL_FETCH_FORMAT: "%d/%m/%y",
    RECORDS_PER_PAGE : 20,

    MASTER_PWD: "asd@12345",

    TBL_USERS : "users",
    TBL_ROLES: "role",
    TBL_ROLE_ACCESS: "role_access",
    TBL_SITE_CONFIG : "site_config",
    TBL_SITE_CONFIG_PARENT : "site_config_parent",
    TBL_ITEM_SECTION : "item_section",
    TBL_ITEMS: "items",
    TBL_META_DETAILS : "meta_details"
}